### ISSUE TITLE
last observation

### ISSUE THREAD

**Issue by dtannebe** [DavidRother/gym-cooking#12]
it seems like there's no 'last observation', meaning there are equally many observations and actions.
but for a (s,a,s') like structure, there needs to be +1 state/observation, and generally, the last observation should be the state of the world AFTER an/the last action.

**Comment by DavidRother** [comment]
The store now holds one more observation that actions etc. fixing this issue.

**Comment by dtannebe** [comment]
after pulling the update, I still have the same problem.

**Comment by dtannebe** [comment]
is it related because I end the game with ESC when my demonstration is finished?

**Comment by DavidRother** [comment]
Yes that was exactly what happened and i fixed it now :)
