### ISSUE TITLE
uniform descpritions

### ISSUE THREAD

**Issue by dtannebe** [DavidRother/gym-cooking#16]
general unified descriptions would be very helpful, like

- all tools should have contents attribute (every tool can only be used if a food is placed on/in it), important
- even more general, every entity that can have something on in should have this field, like counter has tools on it etc.

this would create a uniform world description that is much easier to use.

**Comment by DavidRother** [comment]
Should the floor also have a content attribute and contain an agent or not?

**Comment by dtannebe** [comment]
Mh yes, let's make it completely consistent.

**Comment by DavidRother** [comment]
All relevant objects should now have a content attribute via the abstract ContentObject class and interact properly withing the game
