### ISSUE TITLE
uniform action behavior

### ISSUE THREAD

**Issue by dtannebe** [DavidRother/gym-cooking#19]
actions and objects behave differently.
e.g., I can pick up food from the blender by F, but not from the cutboard, there it gets cut.
should be different actions to pick/place objects or to use a tool for example. currently the blender can't be actively used for example.

**Comment by DavidRother** [comment]
A new action EXECUTE_ACTION has been introduced. It allows an agent to execute the action of an ActionObject when facing in its direction, while standing in front of it. (Conditions of the ActionObject apply). At the same time the INTERACT_PRIMARY action does not execute the action of ActionObjects anymore. 
The new action binding is the key 'e'
